# Maintainer operation after reviewing an intentional dependency patch/update:
# cmake -DGUI_REV_ACCEPT_SOURCE_CHANGES=ON -P tools/update-rev-manifests.cmake
if(NOT GUI_REV_ACCEPT_SOURCE_CHANGES)
    message(FATAL_ERROR "Review the dependency changes, update UPSTREAM.json/PATCHES.md as appropriate, then explicitly pass -DGUI_REV_ACCEPT_SOURCE_CHANGES=ON to refresh source identities.")
endif()
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
foreach(dependency rev rev-deps)
    set(base "${root}/third_party/${dependency}")
    file(GLOB_RECURSE files LIST_DIRECTORIES FALSE RELATIVE "${base}" "${base}/*")
    list(REMOVE_ITEM files SHA256SUMS)
    list(SORT files)
    set(manifest "")
    foreach(file IN LISTS files)
        file(SHA256 "${base}/${file}" digest)
        string(APPEND manifest "${digest}  ${file}\n")
    endforeach()
    file(WRITE "${base}/SHA256SUMS" "${manifest}")
endforeach()
message(STATUS "Refreshed both Rev dependency manifests. Review their diff with the source changes.")
