# Stage portable module interfaces and embed resources using CMake alone.
# No source-tree writes, Python interpreter, asset downloads or runtime paths.
function(gui_rev_write_changed path content)
    if(EXISTS "${path}")
        file(READ "${path}" previous)
        if(previous STREQUAL content)
            return()
        endif()
    endif()
    get_filename_component(parent "${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(WRITE "${path}" "${content}")
endfunction()

function(gui_prepare_rev root output platform)
    file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${root}/source/*.ixx")
    list(SORT sources)
    set(modules)
    set(resources)
    foreach(source IN LISTS sources)
        get_filename_component(name "${source}" NAME)
        string(TOLOWER "${name}" lower)
        if((lower MATCHES "\\.win\\." AND NOT platform STREQUAL "win") OR
           (lower MATCHES "\\.lnx\\." AND NOT platform STREQUAL "lnx") OR
           lower MATCHES "\\.(mac|metal|vulkan)\\.")
            continue()
        endif()
        file(READ "${source}" content)
        if(NOT name STREQUAL "Resource.ixx")
            # Documentation examples are not resource calls. No executable code
            # is removed; only whole comment lines mentioning File(...) are skipped.
            string(REGEX REPLACE "(^|\n)[ \t]*//[^\n]*File\\([^\n]*" "\n" content "${content}")
            string(REGEX MATCHALL "File\\([ \t\r\n]*\"[^\"]+\"[ \t\r\n]*\\)" calls "${content}")
            foreach(call IN LISTS calls)
                string(REGEX REPLACE "^File\\([ \t\r\n]*\"([^\"]+)\"[ \t\r\n]*\\)$" "\\1" reference "${call}")
                if(reference STREQUAL "Rev/resources/Fonts/Arial/Arial.ttf")
                    set(resource "${root}/resources/DejaVuSans.ttf")
                elseif(reference MATCHES "^\\./")
                    get_filename_component(parent "${source}" DIRECTORY)
                    get_filename_component(resource "${parent}/${reference}" ABSOLUTE)
                elseif(reference MATCHES "^Rev/")
                    string(SUBSTRING "${reference}" 4 -1 relative)
                    set(resource "${root}/${relative}")
                else()
                    message(FATAL_ERROR "Unsupported Rev resource ${reference} in ${source}")
                endif()
                if(NOT EXISTS "${resource}")
                    message(FATAL_ERROR "Missing preserved Rev resource: ${resource}")
                endif()
                list(FIND resources "${resource}" index)
                if(index EQUAL -1)
                    list(LENGTH resources index)
                    list(APPEND resources "${resource}")
                endif()
                set(replacement "::Rev::Core::Resource{::gui_rev_resources::resource_${index}, ::gui_rev_resources::resource_${index}_size}")
                string(REPLACE "${call}" "${replacement}" content "${content}")
            endforeach()
        endif()
        string(REPLACE "module;" "module;\n#include \"rev_embedded.hpp\"" content "${content}")
        file(RELATIVE_PATH relative "${root}" "${source}")
        set(target "${output}/${relative}")
        gui_rev_write_changed("${target}" "${content}")
        list(APPEND modules "${target}")
    endforeach()

    # The adapter applies the actual font face for Font.bold; the toolkit's
    # numeric weight field alone does not select a different font resource.
    set(regular_font "${root}/resources/DejaVuSans.ttf")
    set(bold_font "${root}/resources/DejaVuSansMono-Bold.ttf")
    foreach(font IN ITEMS "${regular_font}" "${bold_font}")
        if(NOT EXISTS "${font}")
            message(FATAL_ERROR "Missing preserved Rev font: ${font}")
        endif()
        if(NOT font IN_LIST resources)
            list(APPEND resources "${font}")
        endif()
    endforeach()
    set(header "#pragma once\n#include <cstddef>\nnamespace gui_rev_resources {\n")
    set(implementation "#include \"rev_embedded.hpp\"\nnamespace gui_rev_resources {\n")
    set(index 0)
    foreach(resource IN LISTS resources)
        file(SIZE "${resource}" size)
        file(READ "${resource}" bytes HEX)
        # Hex pairs preserve arbitrary binary assets independently of host locale.
        string(REGEX REPLACE "(..)" "0x\\1," bytes "${bytes}")
        string(REPEAT "0x[0-9a-f][0-9a-f]," 16 row)
        string(REGEX REPLACE "(${row})" "\\1\n" bytes "${bytes}")
        string(APPEND header "extern const unsigned char resource_${index}[];\ninline constexpr std::size_t resource_${index}_size = ${size};\n")
        string(APPEND implementation "const unsigned char resource_${index}[] = {${bytes}};\n")
        math(EXPR index "${index} + 1")
    endforeach()
    foreach(face regular bold)
        list(FIND resources "${${face}_font}" index)
        string(APPEND header "inline constexpr const unsigned char* font_${face} = resource_${index};\ninline constexpr std::size_t font_${face}_size = resource_${index}_size;\n")
    endforeach()
    string(APPEND header "}\n")
    string(APPEND implementation "}\n")
    gui_rev_write_changed("${output}/rev_embedded.hpp" "${header}")
    gui_rev_write_changed("${output}/rev_embedded.cpp" "${implementation}")
    set(GUI_REV_MODULES "${modules}" PARENT_SCOPE)
    list(LENGTH modules module_count)
    list(LENGTH resources resource_count)
    message(STATUS "Staged ${module_count} Rev modules and embedded ${resource_count} local resources")
endfunction()
