function(gui_verify_rev_sources root)
    foreach(dependency rev rev-deps)
        set(base "${root}/third_party/${dependency}")
        set(manifest "${base}/SHA256SUMS")
        if(NOT EXISTS "${manifest}")
            message(FATAL_ERROR "Missing preserved dependency manifest: ${manifest}")
        endif()
        file(STRINGS "${manifest}" entries)
        set(names)
        foreach(entry IN LISTS entries)
            if(NOT entry MATCHES "^([0-9a-f]+)  (.+)$")
                message(FATAL_ERROR "Malformed dependency manifest entry in ${manifest}: ${entry}")
            endif()
            set(expected "${CMAKE_MATCH_1}")
            set(name "${CMAKE_MATCH_2}")
            list(APPEND names "${name}")
            string(LENGTH "${expected}" length)
            if(NOT length EQUAL 64 OR name MATCHES "(^/|(^|/)\\.\\.(/|$)|\\\\)")
                message(FATAL_ERROR "Invalid dependency manifest entry in ${manifest}: ${entry}")
            endif()
            if(NOT EXISTS "${base}/${name}")
                message(FATAL_ERROR "Missing preserved source: ${base}/${name}")
            endif()
            file(SHA256 "${base}/${name}" actual)
            if(NOT actual STREQUAL expected)
                message(FATAL_ERROR "Preserved source checksum mismatch: ${base}/${name}. Restore the source package or intentionally refresh its manifest after reviewing a dependency patch.")
            endif()
        endforeach()
        file(GLOB_RECURSE actual_names LIST_DIRECTORIES FALSE RELATIVE "${base}" "${base}/*")
        list(REMOVE_ITEM actual_names SHA256SUMS)
        list(SORT names)
        list(SORT actual_names)
        if(NOT names STREQUAL actual_names)
            message(FATAL_ERROR "Preserved dependency file inventory differs from ${manifest}. Review added/removed files before refreshing the manifest.")
        endif()
    endforeach()
endfunction()
